try {
  console.log(1);
  throw("e")
  console.log(2);
} catch (error) {
  
}